/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.checkers;

/**
 *
 * @author Rithu
 */
public class CheckersFrame extends javax.swing.JFrame {

    /**
     * Creates new form CheckersFrame
     */
    public CheckersFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPane = new javax.swing.JTabbedPane();
        FirstScreen = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        SecondScreen = new javax.swing.JPanel();
        BackPanel = new javax.swing.JPanel();
        R1C1 = new javax.swing.JButton();
        R1C2 = new javax.swing.JButton();
        R1C3 = new javax.swing.JButton();
        R1C4 = new javax.swing.JButton();
        R1C5 = new javax.swing.JButton();
        R1C6 = new javax.swing.JButton();
        R1C7 = new javax.swing.JButton();
        R1C8 = new javax.swing.JButton();
        R2C1 = new javax.swing.JButton();
        R2C2 = new javax.swing.JButton();
        R2C3 = new javax.swing.JButton();
        R2C4 = new javax.swing.JButton();
        R2C5 = new javax.swing.JButton();
        R2C6 = new javax.swing.JButton();
        R2C7 = new javax.swing.JButton();
        R2C8 = new javax.swing.JButton();
        R3C1 = new javax.swing.JButton();
        R3C2 = new javax.swing.JButton();
        R3C3 = new javax.swing.JButton();
        R3C4 = new javax.swing.JButton();
        R3C5 = new javax.swing.JButton();
        R3C6 = new javax.swing.JButton();
        R3C7 = new javax.swing.JButton();
        R3C8 = new javax.swing.JButton();
        R4C1 = new javax.swing.JButton();
        R4C2 = new javax.swing.JButton();
        R4C3 = new javax.swing.JButton();
        R4C4 = new javax.swing.JButton();
        R4C5 = new javax.swing.JButton();
        R4C6 = new javax.swing.JButton();
        R4C7 = new javax.swing.JButton();
        R4C8 = new javax.swing.JButton();
        R5C1 = new javax.swing.JButton();
        R5C2 = new javax.swing.JButton();
        R5C3 = new javax.swing.JButton();
        R5C4 = new javax.swing.JButton();
        R5C5 = new javax.swing.JButton();
        R5C6 = new javax.swing.JButton();
        R5C7 = new javax.swing.JButton();
        R5C8 = new javax.swing.JButton();
        R6C1 = new javax.swing.JButton();
        R6C2 = new javax.swing.JButton();
        R6C3 = new javax.swing.JButton();
        R6C4 = new javax.swing.JButton();
        R6C5 = new javax.swing.JButton();
        R6C6 = new javax.swing.JButton();
        R6C7 = new javax.swing.JButton();
        R6C8 = new javax.swing.JButton();
        R7C1 = new javax.swing.JButton();
        R7C2 = new javax.swing.JButton();
        R7C3 = new javax.swing.JButton();
        R7C4 = new javax.swing.JButton();
        R7C5 = new javax.swing.JButton();
        R7C6 = new javax.swing.JButton();
        R7C7 = new javax.swing.JButton();
        R7C8 = new javax.swing.JButton();
        R8C1 = new javax.swing.JButton();
        R8C2 = new javax.swing.JButton();
        R8C3 = new javax.swing.JButton();
        R8C4 = new javax.swing.JButton();
        R8C5 = new javax.swing.JButton();
        R8C6 = new javax.swing.JButton();
        R8C7 = new javax.swing.JButton();
        R8C8 = new javax.swing.JButton();
        ThirdScreen = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 51));
        setMaximumSize(new java.awt.Dimension(815, 833));
        setMinimumSize(new java.awt.Dimension(815, 833));
        setPreferredSize(new java.awt.Dimension(815, 833));
        setSize(new java.awt.Dimension(815, 833));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPane.setMaximumSize(new java.awt.Dimension(880, 880));
        MainPane.setMinimumSize(new java.awt.Dimension(880, 880));
        MainPane.setPreferredSize(new java.awt.Dimension(880, 880));

        FirstScreen.setMaximumSize(new java.awt.Dimension(800, 800));
        FirstScreen.setMinimumSize(new java.awt.Dimension(800, 800));
        FirstScreen.setPreferredSize(new java.awt.Dimension(800, 800));
        FirstScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        FirstScreen.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 240, 200));

        MainPane.addTab("tab1", FirstScreen);

        SecondScreen.setBackground(new java.awt.Color(0, 0, 0));
        SecondScreen.setMaximumSize(new java.awt.Dimension(800, 800));
        SecondScreen.setMinimumSize(new java.awt.Dimension(800, 800));
        SecondScreen.setPreferredSize(new java.awt.Dimension(800, 800));
        SecondScreen.setRequestFocusEnabled(false);
        SecondScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackPanel.setBackground(new java.awt.Color(255, 0, 0));
        BackPanel.setMaximumSize(new java.awt.Dimension(800, 800));
        BackPanel.setMinimumSize(new java.awt.Dimension(800, 800));
        BackPanel.setPreferredSize(new java.awt.Dimension(800, 800));
        BackPanel.setLayout(new java.awt.GridLayout(8, 8));

        R1C1.setBackground(new java.awt.Color(250, 236, 226));
        R1C1.setMaximumSize(new java.awt.Dimension(100, 100));
        R1C1.setMinimumSize(new java.awt.Dimension(100, 100));
        R1C1.setPreferredSize(new java.awt.Dimension(100, 100));
        R1C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1C1ActionPerformed(evt);
            }
        });
        BackPanel.add(R1C1);

        R1C2.setBackground(new java.awt.Color(150, 75, 0));
        R1C2.setMaximumSize(new java.awt.Dimension(100, 100));
        R1C2.setMinimumSize(new java.awt.Dimension(100, 100));
        R1C2.setPreferredSize(new java.awt.Dimension(100, 100));
        R1C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1C2ActionPerformed(evt);
            }
        });
        BackPanel.add(R1C2);

        R1C3.setBackground(new java.awt.Color(250, 236, 226));
        R1C3.setMaximumSize(new java.awt.Dimension(100, 100));
        R1C3.setMinimumSize(new java.awt.Dimension(100, 100));
        R1C3.setPreferredSize(new java.awt.Dimension(100, 100));
        R1C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1C3ActionPerformed(evt);
            }
        });
        BackPanel.add(R1C3);

        R1C4.setBackground(new java.awt.Color(150, 75, 0));
        R1C4.setMaximumSize(new java.awt.Dimension(100, 100));
        R1C4.setMinimumSize(new java.awt.Dimension(100, 100));
        R1C4.setPreferredSize(new java.awt.Dimension(100, 100));
        R1C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1C4ActionPerformed(evt);
            }
        });
        BackPanel.add(R1C4);

        R1C5.setBackground(new java.awt.Color(250, 236, 226));
        R1C5.setMaximumSize(new java.awt.Dimension(100, 100));
        R1C5.setMinimumSize(new java.awt.Dimension(100, 100));
        R1C5.setPreferredSize(new java.awt.Dimension(100, 100));
        R1C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1C5ActionPerformed(evt);
            }
        });
        BackPanel.add(R1C5);

        R1C6.setBackground(new java.awt.Color(150, 75, 0));
        R1C6.setMaximumSize(new java.awt.Dimension(100, 100));
        R1C6.setMinimumSize(new java.awt.Dimension(100, 100));
        R1C6.setPreferredSize(new java.awt.Dimension(100, 100));
        R1C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1C6ActionPerformed(evt);
            }
        });
        BackPanel.add(R1C6);

        R1C7.setBackground(new java.awt.Color(250, 236, 226));
        R1C7.setMaximumSize(new java.awt.Dimension(100, 100));
        R1C7.setMinimumSize(new java.awt.Dimension(100, 100));
        R1C7.setPreferredSize(new java.awt.Dimension(100, 100));
        R1C7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1C7ActionPerformed(evt);
            }
        });
        BackPanel.add(R1C7);

        R1C8.setBackground(new java.awt.Color(150, 75, 0));
        R1C8.setMaximumSize(new java.awt.Dimension(100, 100));
        R1C8.setMinimumSize(new java.awt.Dimension(100, 100));
        R1C8.setPreferredSize(new java.awt.Dimension(100, 100));
        R1C8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1C8ActionPerformed(evt);
            }
        });
        BackPanel.add(R1C8);

        R2C1.setBackground(new java.awt.Color(150, 75, 0));
        R2C1.setMaximumSize(new java.awt.Dimension(100, 100));
        R2C1.setMinimumSize(new java.awt.Dimension(100, 100));
        R2C1.setPreferredSize(new java.awt.Dimension(100, 100));
        R2C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2C1ActionPerformed(evt);
            }
        });
        BackPanel.add(R2C1);

        R2C2.setBackground(new java.awt.Color(250, 236, 226));
        R2C2.setMaximumSize(new java.awt.Dimension(100, 100));
        R2C2.setMinimumSize(new java.awt.Dimension(100, 100));
        R2C2.setPreferredSize(new java.awt.Dimension(100, 100));
        R2C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2C2ActionPerformed(evt);
            }
        });
        BackPanel.add(R2C2);

        R2C3.setBackground(new java.awt.Color(150, 75, 0));
        R2C3.setMaximumSize(new java.awt.Dimension(100, 100));
        R2C3.setMinimumSize(new java.awt.Dimension(100, 100));
        R2C3.setPreferredSize(new java.awt.Dimension(100, 100));
        R2C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2C3ActionPerformed(evt);
            }
        });
        BackPanel.add(R2C3);

        R2C4.setBackground(new java.awt.Color(250, 236, 226));
        R2C4.setMaximumSize(new java.awt.Dimension(100, 100));
        R2C4.setMinimumSize(new java.awt.Dimension(100, 100));
        R2C4.setPreferredSize(new java.awt.Dimension(100, 100));
        R2C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2C4ActionPerformed(evt);
            }
        });
        BackPanel.add(R2C4);

        R2C5.setBackground(new java.awt.Color(150, 75, 0));
        R2C5.setMaximumSize(new java.awt.Dimension(100, 100));
        R2C5.setMinimumSize(new java.awt.Dimension(100, 100));
        R2C5.setPreferredSize(new java.awt.Dimension(100, 100));
        R2C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2C5ActionPerformed(evt);
            }
        });
        BackPanel.add(R2C5);

        R2C6.setBackground(new java.awt.Color(250, 236, 226));
        R2C6.setMaximumSize(new java.awt.Dimension(100, 100));
        R2C6.setMinimumSize(new java.awt.Dimension(100, 100));
        R2C6.setPreferredSize(new java.awt.Dimension(100, 100));
        R2C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2C6ActionPerformed(evt);
            }
        });
        BackPanel.add(R2C6);

        R2C7.setBackground(new java.awt.Color(150, 75, 0));
        R2C7.setMaximumSize(new java.awt.Dimension(100, 100));
        R2C7.setMinimumSize(new java.awt.Dimension(100, 100));
        R2C7.setPreferredSize(new java.awt.Dimension(100, 100));
        R2C7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2C7ActionPerformed(evt);
            }
        });
        BackPanel.add(R2C7);

        R2C8.setBackground(new java.awt.Color(250, 236, 226));
        R2C8.setMaximumSize(new java.awt.Dimension(100, 100));
        R2C8.setMinimumSize(new java.awt.Dimension(100, 100));
        R2C8.setPreferredSize(new java.awt.Dimension(100, 100));
        R2C8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2C8ActionPerformed(evt);
            }
        });
        BackPanel.add(R2C8);

        R3C1.setBackground(new java.awt.Color(250, 236, 226));
        R3C1.setMaximumSize(new java.awt.Dimension(100, 100));
        R3C1.setMinimumSize(new java.awt.Dimension(100, 100));
        R3C1.setPreferredSize(new java.awt.Dimension(100, 100));
        R3C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3C1ActionPerformed(evt);
            }
        });
        BackPanel.add(R3C1);

        R3C2.setBackground(new java.awt.Color(150, 75, 0));
        R3C2.setMaximumSize(new java.awt.Dimension(100, 100));
        R3C2.setMinimumSize(new java.awt.Dimension(100, 100));
        R3C2.setPreferredSize(new java.awt.Dimension(100, 100));
        R3C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3C2ActionPerformed(evt);
            }
        });
        BackPanel.add(R3C2);

        R3C3.setBackground(new java.awt.Color(250, 236, 226));
        R3C3.setMaximumSize(new java.awt.Dimension(100, 100));
        R3C3.setMinimumSize(new java.awt.Dimension(100, 100));
        R3C3.setPreferredSize(new java.awt.Dimension(100, 100));
        R3C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3C3ActionPerformed(evt);
            }
        });
        BackPanel.add(R3C3);

        R3C4.setBackground(new java.awt.Color(150, 75, 0));
        R3C4.setMaximumSize(new java.awt.Dimension(100, 100));
        R3C4.setMinimumSize(new java.awt.Dimension(100, 100));
        R3C4.setPreferredSize(new java.awt.Dimension(100, 100));
        R3C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3C4ActionPerformed(evt);
            }
        });
        BackPanel.add(R3C4);

        R3C5.setBackground(new java.awt.Color(250, 236, 226));
        R3C5.setMaximumSize(new java.awt.Dimension(100, 100));
        R3C5.setMinimumSize(new java.awt.Dimension(100, 100));
        R3C5.setPreferredSize(new java.awt.Dimension(100, 100));
        R3C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3C5ActionPerformed(evt);
            }
        });
        BackPanel.add(R3C5);

        R3C6.setBackground(new java.awt.Color(150, 75, 0));
        R3C6.setMaximumSize(new java.awt.Dimension(100, 100));
        R3C6.setMinimumSize(new java.awt.Dimension(100, 100));
        R3C6.setPreferredSize(new java.awt.Dimension(100, 100));
        R3C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3C6ActionPerformed(evt);
            }
        });
        BackPanel.add(R3C6);

        R3C7.setBackground(new java.awt.Color(250, 236, 226));
        R3C7.setMaximumSize(new java.awt.Dimension(100, 100));
        R3C7.setMinimumSize(new java.awt.Dimension(100, 100));
        R3C7.setPreferredSize(new java.awt.Dimension(100, 100));
        R3C7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3C7ActionPerformed(evt);
            }
        });
        BackPanel.add(R3C7);

        R3C8.setBackground(new java.awt.Color(150, 75, 0));
        R3C8.setMaximumSize(new java.awt.Dimension(100, 100));
        R3C8.setMinimumSize(new java.awt.Dimension(100, 100));
        R3C8.setPreferredSize(new java.awt.Dimension(100, 100));
        R3C8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3C8ActionPerformed(evt);
            }
        });
        BackPanel.add(R3C8);

        R4C1.setBackground(new java.awt.Color(150, 75, 0));
        R4C1.setMaximumSize(new java.awt.Dimension(100, 100));
        R4C1.setMinimumSize(new java.awt.Dimension(100, 100));
        R4C1.setPreferredSize(new java.awt.Dimension(100, 100));
        R4C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R4C1ActionPerformed(evt);
            }
        });
        BackPanel.add(R4C1);

        R4C2.setBackground(new java.awt.Color(250, 236, 226));
        R4C2.setMaximumSize(new java.awt.Dimension(100, 100));
        R4C2.setMinimumSize(new java.awt.Dimension(100, 100));
        R4C2.setPreferredSize(new java.awt.Dimension(100, 100));
        R4C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R4C2ActionPerformed(evt);
            }
        });
        BackPanel.add(R4C2);

        R4C3.setBackground(new java.awt.Color(150, 75, 0));
        R4C3.setMaximumSize(new java.awt.Dimension(100, 100));
        R4C3.setMinimumSize(new java.awt.Dimension(100, 100));
        R4C3.setPreferredSize(new java.awt.Dimension(100, 100));
        R4C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R4C3ActionPerformed(evt);
            }
        });
        BackPanel.add(R4C3);

        R4C4.setBackground(new java.awt.Color(250, 236, 226));
        R4C4.setMaximumSize(new java.awt.Dimension(100, 100));
        R4C4.setMinimumSize(new java.awt.Dimension(100, 100));
        R4C4.setPreferredSize(new java.awt.Dimension(100, 100));
        R4C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R4C4ActionPerformed(evt);
            }
        });
        BackPanel.add(R4C4);

        R4C5.setBackground(new java.awt.Color(150, 75, 0));
        R4C5.setMaximumSize(new java.awt.Dimension(100, 100));
        R4C5.setMinimumSize(new java.awt.Dimension(100, 100));
        R4C5.setPreferredSize(new java.awt.Dimension(100, 100));
        R4C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R4C5ActionPerformed(evt);
            }
        });
        BackPanel.add(R4C5);

        R4C6.setBackground(new java.awt.Color(250, 236, 226));
        R4C6.setMaximumSize(new java.awt.Dimension(100, 100));
        R4C6.setMinimumSize(new java.awt.Dimension(100, 100));
        R4C6.setPreferredSize(new java.awt.Dimension(100, 100));
        R4C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R4C6ActionPerformed(evt);
            }
        });
        BackPanel.add(R4C6);

        R4C7.setBackground(new java.awt.Color(150, 75, 0));
        R4C7.setMaximumSize(new java.awt.Dimension(100, 100));
        R4C7.setMinimumSize(new java.awt.Dimension(100, 100));
        R4C7.setPreferredSize(new java.awt.Dimension(100, 100));
        R4C7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R4C7ActionPerformed(evt);
            }
        });
        BackPanel.add(R4C7);

        R4C8.setBackground(new java.awt.Color(250, 236, 226));
        R4C8.setMaximumSize(new java.awt.Dimension(100, 100));
        R4C8.setMinimumSize(new java.awt.Dimension(100, 100));
        R4C8.setPreferredSize(new java.awt.Dimension(100, 100));
        R4C8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R4C8ActionPerformed(evt);
            }
        });
        BackPanel.add(R4C8);

        R5C1.setBackground(new java.awt.Color(250, 236, 226));
        R5C1.setMaximumSize(new java.awt.Dimension(100, 100));
        R5C1.setMinimumSize(new java.awt.Dimension(100, 100));
        R5C1.setPreferredSize(new java.awt.Dimension(100, 100));
        R5C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R5C1ActionPerformed(evt);
            }
        });
        BackPanel.add(R5C1);

        R5C2.setBackground(new java.awt.Color(150, 75, 0));
        R5C2.setMaximumSize(new java.awt.Dimension(100, 100));
        R5C2.setMinimumSize(new java.awt.Dimension(100, 100));
        R5C2.setPreferredSize(new java.awt.Dimension(100, 100));
        R5C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R5C2ActionPerformed(evt);
            }
        });
        BackPanel.add(R5C2);

        R5C3.setBackground(new java.awt.Color(250, 236, 226));
        R5C3.setMaximumSize(new java.awt.Dimension(100, 100));
        R5C3.setMinimumSize(new java.awt.Dimension(100, 100));
        R5C3.setPreferredSize(new java.awt.Dimension(100, 100));
        R5C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R5C3ActionPerformed(evt);
            }
        });
        BackPanel.add(R5C3);

        R5C4.setBackground(new java.awt.Color(150, 75, 0));
        R5C4.setMaximumSize(new java.awt.Dimension(100, 100));
        R5C4.setMinimumSize(new java.awt.Dimension(100, 100));
        R5C4.setPreferredSize(new java.awt.Dimension(100, 100));
        R5C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R5C4ActionPerformed(evt);
            }
        });
        BackPanel.add(R5C4);

        R5C5.setBackground(new java.awt.Color(250, 236, 226));
        R5C5.setMaximumSize(new java.awt.Dimension(100, 100));
        R5C5.setMinimumSize(new java.awt.Dimension(100, 100));
        R5C5.setPreferredSize(new java.awt.Dimension(100, 100));
        R5C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R5C5ActionPerformed(evt);
            }
        });
        BackPanel.add(R5C5);

        R5C6.setBackground(new java.awt.Color(150, 75, 0));
        R5C6.setMaximumSize(new java.awt.Dimension(100, 100));
        R5C6.setMinimumSize(new java.awt.Dimension(100, 100));
        R5C6.setPreferredSize(new java.awt.Dimension(100, 100));
        R5C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R5C6ActionPerformed(evt);
            }
        });
        BackPanel.add(R5C6);

        R5C7.setBackground(new java.awt.Color(250, 236, 226));
        R5C7.setMaximumSize(new java.awt.Dimension(100, 100));
        R5C7.setMinimumSize(new java.awt.Dimension(100, 100));
        R5C7.setPreferredSize(new java.awt.Dimension(100, 100));
        R5C7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R5C7ActionPerformed(evt);
            }
        });
        BackPanel.add(R5C7);

        R5C8.setBackground(new java.awt.Color(150, 75, 0));
        R5C8.setMaximumSize(new java.awt.Dimension(100, 100));
        R5C8.setMinimumSize(new java.awt.Dimension(100, 100));
        R5C8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R5C8ActionPerformed(evt);
            }
        });
        BackPanel.add(R5C8);

        R6C1.setBackground(new java.awt.Color(150, 75, 0));
        R6C1.setMaximumSize(new java.awt.Dimension(100, 100));
        R6C1.setMinimumSize(new java.awt.Dimension(100, 100));
        R6C1.setPreferredSize(new java.awt.Dimension(100, 100));
        R6C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R6C1ActionPerformed(evt);
            }
        });
        BackPanel.add(R6C1);

        R6C2.setBackground(new java.awt.Color(250, 236, 226));
        R6C2.setMaximumSize(new java.awt.Dimension(100, 100));
        R6C2.setMinimumSize(new java.awt.Dimension(100, 100));
        R6C2.setPreferredSize(new java.awt.Dimension(100, 100));
        R6C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R6C2ActionPerformed(evt);
            }
        });
        BackPanel.add(R6C2);

        R6C3.setBackground(new java.awt.Color(150, 75, 0));
        R6C3.setMaximumSize(new java.awt.Dimension(100, 100));
        R6C3.setMinimumSize(new java.awt.Dimension(100, 100));
        R6C3.setPreferredSize(new java.awt.Dimension(100, 100));
        R6C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R6C3ActionPerformed(evt);
            }
        });
        BackPanel.add(R6C3);

        R6C4.setBackground(new java.awt.Color(250, 236, 226));
        R6C4.setMaximumSize(new java.awt.Dimension(100, 100));
        R6C4.setMinimumSize(new java.awt.Dimension(100, 100));
        R6C4.setPreferredSize(new java.awt.Dimension(100, 100));
        R6C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R6C4ActionPerformed(evt);
            }
        });
        BackPanel.add(R6C4);

        R6C5.setBackground(new java.awt.Color(150, 75, 0));
        R6C5.setMaximumSize(new java.awt.Dimension(100, 100));
        R6C5.setMinimumSize(new java.awt.Dimension(100, 100));
        R6C5.setPreferredSize(new java.awt.Dimension(100, 100));
        R6C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R6C5ActionPerformed(evt);
            }
        });
        BackPanel.add(R6C5);

        R6C6.setBackground(new java.awt.Color(250, 236, 226));
        R6C6.setMaximumSize(new java.awt.Dimension(100, 100));
        R6C6.setMinimumSize(new java.awt.Dimension(100, 100));
        R6C6.setPreferredSize(new java.awt.Dimension(100, 100));
        R6C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R6C6ActionPerformed(evt);
            }
        });
        BackPanel.add(R6C6);

        R6C7.setBackground(new java.awt.Color(150, 75, 0));
        R6C7.setMaximumSize(new java.awt.Dimension(100, 100));
        R6C7.setMinimumSize(new java.awt.Dimension(100, 100));
        R6C7.setPreferredSize(new java.awt.Dimension(100, 100));
        R6C7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R6C7ActionPerformed(evt);
            }
        });
        BackPanel.add(R6C7);

        R6C8.setBackground(new java.awt.Color(250, 236, 226));
        R6C8.setMaximumSize(new java.awt.Dimension(100, 100));
        R6C8.setMinimumSize(new java.awt.Dimension(100, 100));
        R6C8.setPreferredSize(new java.awt.Dimension(100, 100));
        R6C8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R6C8ActionPerformed(evt);
            }
        });
        BackPanel.add(R6C8);

        R7C1.setBackground(new java.awt.Color(250, 236, 226));
        R7C1.setMaximumSize(new java.awt.Dimension(100, 100));
        R7C1.setMinimumSize(new java.awt.Dimension(100, 100));
        R7C1.setPreferredSize(new java.awt.Dimension(100, 100));
        R7C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R7C1ActionPerformed(evt);
            }
        });
        BackPanel.add(R7C1);

        R7C2.setBackground(new java.awt.Color(150, 75, 0));
        R7C2.setMaximumSize(new java.awt.Dimension(100, 100));
        R7C2.setMinimumSize(new java.awt.Dimension(100, 100));
        R7C2.setPreferredSize(new java.awt.Dimension(100, 100));
        R7C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R7C2ActionPerformed(evt);
            }
        });
        BackPanel.add(R7C2);

        R7C3.setBackground(new java.awt.Color(250, 236, 226));
        R7C3.setMaximumSize(new java.awt.Dimension(100, 100));
        R7C3.setMinimumSize(new java.awt.Dimension(100, 100));
        R7C3.setPreferredSize(new java.awt.Dimension(100, 100));
        R7C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R7C3ActionPerformed(evt);
            }
        });
        BackPanel.add(R7C3);

        R7C4.setBackground(new java.awt.Color(150, 75, 0));
        R7C4.setMaximumSize(new java.awt.Dimension(100, 100));
        R7C4.setMinimumSize(new java.awt.Dimension(100, 100));
        R7C4.setPreferredSize(new java.awt.Dimension(100, 100));
        R7C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R7C4ActionPerformed(evt);
            }
        });
        BackPanel.add(R7C4);

        R7C5.setBackground(new java.awt.Color(250, 236, 226));
        R7C5.setMaximumSize(new java.awt.Dimension(100, 100));
        R7C5.setMinimumSize(new java.awt.Dimension(100, 100));
        R7C5.setPreferredSize(new java.awt.Dimension(100, 100));
        R7C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R7C5ActionPerformed(evt);
            }
        });
        BackPanel.add(R7C5);

        R7C6.setBackground(new java.awt.Color(150, 75, 0));
        R7C6.setMaximumSize(new java.awt.Dimension(100, 100));
        R7C6.setMinimumSize(new java.awt.Dimension(100, 100));
        R7C6.setPreferredSize(new java.awt.Dimension(100, 100));
        R7C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R7C6ActionPerformed(evt);
            }
        });
        BackPanel.add(R7C6);

        R7C7.setBackground(new java.awt.Color(250, 236, 226));
        R7C7.setMaximumSize(new java.awt.Dimension(100, 100));
        R7C7.setMinimumSize(new java.awt.Dimension(100, 100));
        R7C7.setPreferredSize(new java.awt.Dimension(100, 100));
        R7C7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R7C7ActionPerformed(evt);
            }
        });
        BackPanel.add(R7C7);

        R7C8.setBackground(new java.awt.Color(150, 75, 0));
        R7C8.setMaximumSize(new java.awt.Dimension(100, 100));
        R7C8.setMinimumSize(new java.awt.Dimension(100, 100));
        R7C8.setPreferredSize(new java.awt.Dimension(100, 100));
        R7C8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R7C8ActionPerformed(evt);
            }
        });
        BackPanel.add(R7C8);

        R8C1.setBackground(new java.awt.Color(150, 75, 0));
        R8C1.setMaximumSize(new java.awt.Dimension(100, 100));
        R8C1.setMinimumSize(new java.awt.Dimension(100, 100));
        R8C1.setPreferredSize(new java.awt.Dimension(100, 100));
        R8C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R8C1ActionPerformed(evt);
            }
        });
        BackPanel.add(R8C1);

        R8C2.setBackground(new java.awt.Color(250, 236, 226));
        R8C2.setToolTipText("");
        R8C2.setMaximumSize(new java.awt.Dimension(100, 100));
        R8C2.setMinimumSize(new java.awt.Dimension(100, 100));
        R8C2.setPreferredSize(new java.awt.Dimension(100, 100));
        R8C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R8C2ActionPerformed(evt);
            }
        });
        BackPanel.add(R8C2);

        R8C3.setBackground(new java.awt.Color(150, 75, 0));
        R8C3.setMaximumSize(new java.awt.Dimension(100, 100));
        R8C3.setMinimumSize(new java.awt.Dimension(100, 100));
        R8C3.setPreferredSize(new java.awt.Dimension(100, 100));
        R8C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R8C3ActionPerformed(evt);
            }
        });
        BackPanel.add(R8C3);

        R8C4.setBackground(new java.awt.Color(250, 236, 226));
        R8C4.setMaximumSize(new java.awt.Dimension(100, 100));
        R8C4.setMinimumSize(new java.awt.Dimension(100, 100));
        R8C4.setPreferredSize(new java.awt.Dimension(100, 100));
        R8C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R8C4ActionPerformed(evt);
            }
        });
        BackPanel.add(R8C4);

        R8C5.setBackground(new java.awt.Color(150, 75, 0));
        R8C5.setMaximumSize(new java.awt.Dimension(100, 100));
        R8C5.setMinimumSize(new java.awt.Dimension(100, 100));
        R8C5.setPreferredSize(new java.awt.Dimension(100, 100));
        R8C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R8C5ActionPerformed(evt);
            }
        });
        BackPanel.add(R8C5);

        R8C6.setBackground(new java.awt.Color(250, 236, 226));
        R8C6.setMaximumSize(new java.awt.Dimension(100, 100));
        R8C6.setMinimumSize(new java.awt.Dimension(100, 100));
        R8C6.setPreferredSize(new java.awt.Dimension(100, 100));
        R8C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R8C6ActionPerformed(evt);
            }
        });
        BackPanel.add(R8C6);

        R8C7.setBackground(new java.awt.Color(150, 75, 0));
        R8C7.setMaximumSize(new java.awt.Dimension(100, 100));
        R8C7.setMinimumSize(new java.awt.Dimension(100, 100));
        R8C7.setPreferredSize(new java.awt.Dimension(100, 100));
        BackPanel.add(R8C7);

        R8C8.setBackground(new java.awt.Color(250, 236, 226));
        R8C8.setMaximumSize(new java.awt.Dimension(100, 100));
        R8C8.setMinimumSize(new java.awt.Dimension(100, 100));
        R8C8.setPreferredSize(new java.awt.Dimension(100, 100));
        R8C8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R8C8ActionPerformed(evt);
            }
        });
        BackPanel.add(R8C8);

        SecondScreen.add(BackPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 800));

        MainPane.addTab("tab2", SecondScreen);

        ThirdScreen.setMaximumSize(new java.awt.Dimension(800, 800));
        ThirdScreen.setMinimumSize(new java.awt.Dimension(800, 800));
        ThirdScreen.setPreferredSize(new java.awt.Dimension(800, 800));
        ThirdScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        MainPane.addTab("tab3", ThirdScreen);

        getContentPane().add(MainPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 800, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void R1C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1C3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R1C3ActionPerformed

    private void R1C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1C1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R1C1ActionPerformed

    private void R1C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1C2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R1C2ActionPerformed

    private void R1C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1C4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R1C4ActionPerformed

    private void R1C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1C5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R1C5ActionPerformed

    private void R1C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1C6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R1C6ActionPerformed

    private void R1C7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1C7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R1C7ActionPerformed

    private void R1C8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1C8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R1C8ActionPerformed

    private void R2C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2C1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R2C1ActionPerformed

    private void R2C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2C2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R2C2ActionPerformed

    private void R2C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2C3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R2C3ActionPerformed

    private void R2C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2C4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R2C4ActionPerformed

    private void R2C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2C5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R2C5ActionPerformed

    private void R2C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2C6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R2C6ActionPerformed

    private void R2C7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2C7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R2C7ActionPerformed

    private void R2C8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2C8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R2C8ActionPerformed

    private void R3C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3C1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R3C1ActionPerformed

    private void R3C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3C2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R3C2ActionPerformed

    private void R3C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3C3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R3C3ActionPerformed

    private void R3C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3C4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R3C4ActionPerformed

    private void R3C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3C5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R3C5ActionPerformed

    private void R3C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3C6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R3C6ActionPerformed

    private void R3C7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3C7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R3C7ActionPerformed

    private void R3C8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3C8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R3C8ActionPerformed

    private void R4C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R4C1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R4C1ActionPerformed

    private void R4C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R4C2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R4C2ActionPerformed

    private void R4C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R4C3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R4C3ActionPerformed

    private void R4C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R4C4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R4C4ActionPerformed

    private void R4C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R4C5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R4C5ActionPerformed

    private void R4C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R4C6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R4C6ActionPerformed

    private void R4C7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R4C7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R4C7ActionPerformed

    private void R4C8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R4C8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R4C8ActionPerformed

    private void R5C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R5C1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R5C1ActionPerformed

    private void R5C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R5C2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R5C2ActionPerformed

    private void R5C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R5C3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R5C3ActionPerformed

    private void R5C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R5C4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R5C4ActionPerformed

    private void R5C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R5C5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R5C5ActionPerformed

    private void R5C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R5C6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R5C6ActionPerformed

    private void R5C7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R5C7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R5C7ActionPerformed

    private void R5C8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R5C8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R5C8ActionPerformed

    private void R6C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R6C1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R6C1ActionPerformed

    private void R6C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R6C2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R6C2ActionPerformed

    private void R6C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R6C3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R6C3ActionPerformed

    private void R6C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R6C4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R6C4ActionPerformed

    private void R6C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R6C5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R6C5ActionPerformed

    private void R6C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R6C6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R6C6ActionPerformed

    private void R6C7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R6C7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R6C7ActionPerformed

    private void R6C8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R6C8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R6C8ActionPerformed

    private void R7C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R7C1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R7C1ActionPerformed

    private void R7C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R7C2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R7C2ActionPerformed

    private void R7C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R7C3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R7C3ActionPerformed

    private void R7C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R7C4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R7C4ActionPerformed

    private void R7C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R7C5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R7C5ActionPerformed

    private void R7C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R7C6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R7C6ActionPerformed

    private void R7C7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R7C7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R7C7ActionPerformed

    private void R7C8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R7C8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R7C8ActionPerformed

    private void R8C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R8C1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R8C1ActionPerformed

    private void R8C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R8C2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R8C2ActionPerformed

    private void R8C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R8C3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R8C3ActionPerformed

    private void R8C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R8C4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R8C4ActionPerformed

    private void R8C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R8C5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R8C5ActionPerformed

    private void R8C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R8C6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R8C6ActionPerformed

    private void R8C8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R8C8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R8C8ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackPanel;
    private javax.swing.JPanel FirstScreen;
    private javax.swing.JTabbedPane MainPane;
    private javax.swing.JButton R1C1;
    private javax.swing.JButton R1C2;
    private javax.swing.JButton R1C3;
    private javax.swing.JButton R1C4;
    private javax.swing.JButton R1C5;
    private javax.swing.JButton R1C6;
    private javax.swing.JButton R1C7;
    private javax.swing.JButton R1C8;
    private javax.swing.JButton R2C1;
    private javax.swing.JButton R2C2;
    private javax.swing.JButton R2C3;
    private javax.swing.JButton R2C4;
    private javax.swing.JButton R2C5;
    private javax.swing.JButton R2C6;
    private javax.swing.JButton R2C7;
    private javax.swing.JButton R2C8;
    private javax.swing.JButton R3C1;
    private javax.swing.JButton R3C2;
    private javax.swing.JButton R3C3;
    private javax.swing.JButton R3C4;
    private javax.swing.JButton R3C5;
    private javax.swing.JButton R3C6;
    private javax.swing.JButton R3C7;
    private javax.swing.JButton R3C8;
    private javax.swing.JButton R4C1;
    private javax.swing.JButton R4C2;
    private javax.swing.JButton R4C3;
    private javax.swing.JButton R4C4;
    private javax.swing.JButton R4C5;
    private javax.swing.JButton R4C6;
    private javax.swing.JButton R4C7;
    private javax.swing.JButton R4C8;
    private javax.swing.JButton R5C1;
    private javax.swing.JButton R5C2;
    private javax.swing.JButton R5C3;
    private javax.swing.JButton R5C4;
    private javax.swing.JButton R5C5;
    private javax.swing.JButton R5C6;
    private javax.swing.JButton R5C7;
    private javax.swing.JButton R5C8;
    private javax.swing.JButton R6C1;
    private javax.swing.JButton R6C2;
    private javax.swing.JButton R6C3;
    private javax.swing.JButton R6C4;
    private javax.swing.JButton R6C5;
    private javax.swing.JButton R6C6;
    private javax.swing.JButton R6C7;
    private javax.swing.JButton R6C8;
    private javax.swing.JButton R7C1;
    private javax.swing.JButton R7C2;
    private javax.swing.JButton R7C3;
    private javax.swing.JButton R7C4;
    private javax.swing.JButton R7C5;
    private javax.swing.JButton R7C6;
    private javax.swing.JButton R7C7;
    private javax.swing.JButton R7C8;
    private javax.swing.JButton R8C1;
    private javax.swing.JButton R8C2;
    private javax.swing.JButton R8C3;
    private javax.swing.JButton R8C4;
    private javax.swing.JButton R8C5;
    private javax.swing.JButton R8C6;
    private javax.swing.JButton R8C7;
    private javax.swing.JButton R8C8;
    private javax.swing.JPanel SecondScreen;
    private javax.swing.JPanel ThirdScreen;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
